In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd
reviews = pd.read_csv("/content/meets.csv", index_col=0)

In [ ]:
reviews.head()

,MeetPath,Federation,Date,MeetCountry,MeetState,MeetTown,MeetName
MeetID,,,,,,,
0,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
1,365strong/1602,365Strong,2016-11-19,USA,MO,Ozark,Thanksgiving Powerlifting Classic
2,365strong/1603,365Strong,2016-07-09,USA,NC,Charlotte,Charlotte Europa Games
3,365strong/1604,365Strong,2016-06-11,USA,SC,Rock Hill,Carolina Cup Push Pull Challenge
4,365strong/1605,365Strong,2016-04-10,USA,SC,Rock Hill,Eastern USA Challenge

In [ ]:
reviews.MeetState.dtype

dtype('O')

In [ ]:
reviews.dtypes

MeetPath       object
Federation     object
Date           object
MeetCountry    object
MeetState      object
MeetTown       object
MeetName       object
dtype: object

In [ ]:
reviews[reviews.MeetTown.isnull()]

,MeetPath,Federation,Date,MeetCountry,MeetState,MeetTown,MeetName
MeetID,,,,,,,
22,apa/1001,APA,2010-11-13,USA,FL,NaN,Ironfest Challenge
23,apa/1002,APA,2010-04-17,USA,NaN,NaN,Raw Nationals
57,apc/1703,APC,2017-03-11,USA,FL,NaN,Florida Panhandle Dominion
59,apf/1401,WPC,2014-11-10,USA,FL,NaN,World Championships
61,apf/1502,APF,2015-04-15,USA,FL,NaN,Gulf Coast Winter Bash
...,...,...,...,...,...,...,...
7689,uspa/0276,IPL,2013-10-12,Brazil,SP,NaN,Brazil National Powerlifting Championships
8441,welshpa/1701,WelshPA,2017-02-18,Wales,NaN,NaN,Welsh Championships
8443,wpc-rus/1501,WPC,2015-11-21,Russia,NaN,NaN,SN PRO Open Cup
8462,wrpf/1713,WRPF,2017-07-01,Colombia,NaN,NaN,Saulpower III
8465,wrpf-can/1701,WRPF-CAN,2017-05-13,Canada,NaN,NaN,Compétition du 13 Mai 2017

In [ ]:
reviews.MeetName.fillna("Unknown")

MeetID
0       2016 Junior & Senior National Powerlifting Cha...
1                       Thanksgiving Powerlifting Classic
2                                  Charlotte Europa Games
3                        Carolina Cup Push Pull Challenge
4                                   Eastern USA Challenge
                              ...
8477                                             2015 XPC
8478                            2016 XPC Bench Freak Show
8479                                2016 XPC Elite Finals
8480                                  2016 XPC PRO Finals
8481                                      2017 XPC Finals
Name: MeetName, Length: 8482, dtype: object

In [ ]:
reviews.MeetCountry.replace("USA", "Pakistan")

MeetID
0       Pakistan
1       Pakistan
2       Pakistan
3       Pakistan
4       Pakistan
          ...
8477    Pakistan
8478    Pakistan
8479    Pakistan
8480    Pakistan
8481    Pakistan
Name: MeetCountry, Length: 8482, dtype: object